// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.3
// source: listing.proto

package listing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Listing_ListingCategory int32

const (
	Listing_Laundry          Listing_ListingCategory = 0
	Listing_Shopping         Listing_ListingCategory = 1
	Listing_Transportation   Listing_ListingCategory = 2
	Listing_Cooking          Listing_ListingCategory = 3
	Listing_Cleaning         Listing_ListingCategory = 4
	Listing_AutoRepairs      Listing_ListingCategory = 5
	Listing_ShortTermJobs    Listing_ListingCategory = 6
	Listing_Farming          Listing_ListingCategory = 7
	Listing_Delivery         Listing_ListingCategory = 8
	Listing_BabySitting      Listing_ListingCategory = 9
	Listing_HeavyLifting     Listing_ListingCategory = 10
	Listing_Tutoring         Listing_ListingCategory = 11
	Listing_Landscaping      Listing_ListingCategory = 12
	Listing_ConstructionWork Listing_ListingCategory = 13
	Listing_Others           Listing_ListingCategory = 25
	Listing_Caterers         Listing_ListingCategory = 14
	Listing_HouseHold        Listing_ListingCategory = 15
	Listing_Baking           Listing_ListingCategory = 16
	Listing_MakeUp           Listing_ListingCategory = 17
)

// Enum value maps for Listing_ListingCategory.
var (
	Listing_ListingCategory_name = map[int32]string{
		0:  "Laundry",
		1:  "Shopping",
		2:  "Transportation",
		3:  "Cooking",
		4:  "Cleaning",
		5:  "AutoRepairs",
		6:  "ShortTermJobs",
		7:  "Farming",
		8:  "Delivery",
		9:  "BabySitting",
		10: "HeavyLifting",
		11: "Tutoring",
		12: "Landscaping",
		13: "ConstructionWork",
		25: "Others",
		14: "Caterers",
		15: "HouseHold",
		16: "Baking",
		17: "MakeUp",
	}
	Listing_ListingCategory_value = map[string]int32{
		"Laundry":          0,
		"Shopping":         1,
		"Transportation":   2,
		"Cooking":          3,
		"Cleaning":         4,
		"AutoRepairs":      5,
		"ShortTermJobs":    6,
		"Farming":          7,
		"Delivery":         8,
		"BabySitting":      9,
		"HeavyLifting":     10,
		"Tutoring":         11,
		"Landscaping":      12,
		"ConstructionWork": 13,
		"Others":           25,
		"Caterers":         14,
		"HouseHold":        15,
		"Baking":           16,
		"MakeUp":           17,
	}
)

func (x Listing_ListingCategory) Enum() *Listing_ListingCategory {
	p := new(Listing_ListingCategory)
	*p = x
	return p
}

func (x Listing_ListingCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Listing_ListingCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_listing_proto_enumTypes[0].Descriptor()
}

func (Listing_ListingCategory) Type() protoreflect.EnumType {
	return &file_listing_proto_enumTypes[0]
}

func (x Listing_ListingCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Listing_ListingCategory.Descriptor instead.
func (Listing_ListingCategory) EnumDescriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 0}
}

// A `listing` template describing its properties
type Listing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description     string                  `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Id              string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"` // Unique ID number for this person.
	ListingCategory Listing_ListingCategory `protobuf:"varint,3,opt,name=listingCategory,proto3,enum=listing.Listing_ListingCategory" json:"listingCategory,omitempty"`
	ImageUri        string                  `protobuf:"bytes,4,opt,name=imageUri,proto3" json:"imageUri,omitempty"`
	Owner           *Listing_OwnerDetail    `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Location        *Listing_Location       `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	CreationTime    *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
}

func (x *Listing) Reset() {
	*x = Listing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0}
}

func (x *Listing) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Listing) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Listing) GetListingCategory() Listing_ListingCategory {
	if x != nil {
		return x.ListingCategory
	}
	return Listing_Laundry
}

func (x *Listing) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *Listing) GetOwner() *Listing_OwnerDetail {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Listing) GetLocation() *Listing_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Listing) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

// A list of `listings`.
type Listings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listing []*Listing `protobuf:"bytes,1,rep,name=listing,proto3" json:"listing,omitempty"`
}

func (x *Listings) Reset() {
	*x = Listings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listings) ProtoMessage() {}

func (x *Listings) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listings.ProtoReflect.Descriptor instead.
func (*Listings) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{1}
}

func (x *Listings) GetListing() []*Listing {
	if x != nil {
		return x.Listing
	}
	return nil
}

type Listing_OwnerDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email       string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ImageUri    string `protobuf:"bytes,2,opt,name=imageUri,proto3" json:"imageUri,omitempty"`
	ProfileLink string `protobuf:"bytes,3,opt,name=profileLink,proto3" json:"profileLink,omitempty"`
}

func (x *Listing_OwnerDetail) Reset() {
	*x = Listing_OwnerDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing_OwnerDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_OwnerDetail) ProtoMessage() {}

func (x *Listing_OwnerDetail) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_OwnerDetail.ProtoReflect.Descriptor instead.
func (*Listing_OwnerDetail) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Listing_OwnerDetail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Listing_OwnerDetail) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *Listing_OwnerDetail) GetProfileLink() string {
	if x != nil {
		return x.ProfileLink
	}
	return ""
}

type Listing_Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longitude string `protobuf:"bytes,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude  string `protobuf:"bytes,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
}

func (x *Listing_Location) Reset() {
	*x = Listing_Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listing_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Location) ProtoMessage() {}

func (x *Listing_Location) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Location.ProtoReflect.Descriptor instead.
func (*Listing_Location) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Listing_Location) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *Listing_Location) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

var File_listing_proto protoreflect.FileDescriptor

var file_listing_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xad, 0x06, 0x0a, 0x07, 0x4c, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x4a, 0x0a, 0x0f, 0x6c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x20, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x52, 0x0f, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x69, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x69, 0x12,
	0x32, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3e, 0x0a, 0x0c, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x61, 0x0a, 0x0b, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x69, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x1a, 0x44, 0x0a,
	0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f,
	0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x22, 0xb3, 0x02, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x61, 0x75, 0x6e, 0x64,
	0x72, 0x79, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x10,
	0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x70, 0x61, 0x69, 0x72, 0x73,
	0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x4a,
	0x6f, 0x62, 0x73, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x61, 0x72, 0x6d, 0x69, 0x6e, 0x67,
	0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x10, 0x08,
	0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x61, 0x62, 0x79, 0x53, 0x69, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x10,
	0x09, 0x12, 0x10, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x76, 0x79, 0x4c, 0x69, 0x66, 0x74, 0x69, 0x6e,
	0x67, 0x10, 0x0a, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x10,
	0x0b, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x69, 0x6e, 0x67,
	0x10, 0x0c, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x10, 0x0d, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x74, 0x68, 0x65,
	0x72, 0x73, 0x10, 0x19, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x72, 0x65, 0x72, 0x73,
	0x10, 0x0e, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x10,
	0x0f, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x10, 0x10, 0x12, 0x0a, 0x0a,
	0x06, 0x4d, 0x61, 0x6b, 0x65, 0x55, 0x70, 0x10, 0x11, 0x22, 0x36, 0x0a, 0x08, 0x4c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6c, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_listing_proto_rawDescOnce sync.Once
	file_listing_proto_rawDescData = file_listing_proto_rawDesc
)

func file_listing_proto_rawDescGZIP() []byte {
	file_listing_proto_rawDescOnce.Do(func() {
		file_listing_proto_rawDescData = protoimpl.X.CompressGZIP(file_listing_proto_rawDescData)
	})
	return file_listing_proto_rawDescData
}

var file_listing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_listing_proto_goTypes = []interface{}{
	(Listing_ListingCategory)(0),  // 0: listing.Listing.ListingCategory
	(*Listing)(nil),               // 1: listing.Listing
	(*Listings)(nil),              // 2: listing.Listings
	(*Listing_OwnerDetail)(nil),   // 3: listing.Listing.OwnerDetail
	(*Listing_Location)(nil),      // 4: listing.Listing.Location
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_listing_proto_depIdxs = []int32{
	0, // 0: listing.Listing.listingCategory:type_name -> listing.Listing.ListingCategory
	3, // 1: listing.Listing.owner:type_name -> listing.Listing.OwnerDetail
	4, // 2: listing.Listing.location:type_name -> listing.Listing.Location
	5, // 3: listing.Listing.creationTime:type_name -> google.protobuf.Timestamp
	1, // 4: listing.Listings.listing:type_name -> listing.Listing
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_listing_proto_init() }
func file_listing_proto_init() {
	if File_listing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_listing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing_OwnerDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listing_Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_listing_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_listing_proto_goTypes,
		DependencyIndexes: file_listing_proto_depIdxs,
		EnumInfos:         file_listing_proto_enumTypes,
		MessageInfos:      file_listing_proto_msgTypes,
	}.Build()
	File_listing_proto = out.File
	file_listing_proto_rawDesc = nil
	file_listing_proto_goTypes = nil
	file_listing_proto_depIdxs = nil
}
